### ISSUE TITLE
Default length for !top

### ISSUE THREAD

**Issue by FrankWhoee** [FrankWhoee/HaliteBot#4]
There should be a default length set for !top so when !top is typed, a default amount of players will be listed.

**Comment by RaviTeja1274** [comment]
Hi,
I would like to work on this

**Comment by FrankWhoee** [comment]
@RaviTeja1274 Sure, just write some code, and open up a pull request when you're done!

**Comment by RaviTeja1274** [comment]
Hi,
opened pull request

https://github.com/FrankWhoee/HaliteBot/pull/11
